import test from 'node:test';
import assert from 'node:assert/strict';
import {CafeRoom} from '../server/room.js';
import {saveRoom,loadRoom} from '../server/persistence.js';
import {createCafeServer} from '../server/http.js';
import {cleanName,escapeHTML} from '../src/online/protocol.js';

function setup(gameId='uno'){let now=1000;const room=new CafeRoom({now:()=>now});const a=room.join('Юрий'),b=room.join('Анна');room.command(a.token,{type:'invite',to:b.id,gameId});room.command(b.token,{type:'respond',id:room.poll(b.token).incoming.id,accept:true});return {room,a,b,time:t=>now=t};}
test('presence, name sanitation, decline and invitation expiration',()=>{let now=0;const r=new CafeRoom({now:()=>now}),a=r.join(' Юрий '),b=r.join('Анна');assert.equal(r.poll(a.token).guests.length,2);r.command(a.token,{type:'name',name:' <b>Юрий</b>\u202e '});assert.equal(r.poll(b.token).guests[0].name,'bЮрий/b');r.command(a.token,{type:'invite',to:b.id,gameId:'poker'});assert.throws(()=>r.command(a.token,{type:'respond',id:r.poll(b.token).incoming.id,accept:true}));r.command(b.token,{type:'respond',id:r.poll(b.token).incoming.id,accept:false});assert.match(r.poll(a.token).notice,/не готов/);r.command(a.token,{type:'invite',to:b.id,gameId:'uno'});now=31000;assert.equal(r.poll(b.token).incoming,null);assert.equal(r.poll(a.token).outgoing,null);assert.equal(cleanName(''), 'Гость');assert.equal(escapeHTML('"<img>&'), '&quot;&lt;img&gt;&amp;');});
test('a match exposes only own cards and no deck identities',()=>{for(const id of ['uno','durak','poker']){const {room,a,b}=setup(id);const x=room.poll(a.token).match,y=room.poll(b.token).match;assert.equal(x.id,y.id);assert.equal(x.seat,0);assert.equal(y.seat,1);assert.ok(x.state.hands[0][0]?.id!==undefined);assert.ok(x.state.hands[1].every(c=>c===null));assert.ok(y.state.hands[0].every(c=>c===null));assert.ok(x.state.draw.every(c=>c===null));assert.equal(JSON.stringify(x).includes(a.token),false);}});
test('reject wrong player, stale revision, duplicate action and third party',()=>{const {room,a,b}=setup('checkers'),c=room.join('Третий'),m=room.poll(a.token).match;const action={type:'action',match:m.id,revision:m.revision,action:{from:42,to:33}};assert.throws(()=>room.command(b.token,action));assert.throws(()=>room.command(c.token,action));room.command(a.token,action);assert.throws(()=>room.command(a.token,action));assert.equal(room.poll(b.token).match.state.actor,1);assert.throws(()=>room.command(c.token,{type:'invite',to:a.id,gameId:'uno'}));});
test('disconnect cancels match, reconnect within grace retains it',()=>{const {room,a,b,time}=setup();time(25000);assert.ok(room.poll(a.token).match);time(37000);assert.equal(room.poll(a.token).match,null);assert.match(room.poll(a.token).notice,/отключился/);assert.throws(()=>room.poll(b.token),/SESSION_EXPIRED/);});
test('all turn games survive database serialization and finish without bots on server',()=>{for(const gameId of ['uno','durak','checkers','poker']){let {room,a,b}=setup(gameId);const tokens=[a.token,b.token];for(let step=0;step<6000;step++){const m=[...room.matches.values()][0];if(m.game.done)break;const engine=m.game;let move;const act=engine.act;engine.act=a=>{move=a;return true;};engine.bot();engine.act=act;room.command(tokens[engine.actor],{type:'action',match:m.id,revision:m.revision,action:move});room=loadRoom(saveRoom(room),{now:()=>1000});}assert.ok([...room.matches.values()][0].game.done,gameId+' must finish');}});
test('croissant gives each human independent target and no automatic bot scores',()=>{const {room,a,b,time}=setup('croissant');const m=room.poll(b.token).match;room.command(b.token,{type:'action',match:m.id,revision:m.revision,target:m.state.target,action:{slot:m.state.target}});assert.deepEqual(room.poll(a.token).match.state.scores,[0,1]);time(32000);const result=room.poll(a.token).match;assert.equal(result.state.done,true);assert.deepEqual(result.state.scores,[0,1]);assert.equal(result.state.winner,1);});
test('leaving clears both players, and a new invitation is possible',()=>{const {room,a,b}=setup();room.command(a.token,{type:'leave'});assert.equal(room.poll(b.token).match,null);room.command(b.token,{type:'invite',to:a.id,gameId:'durak'});assert.ok(room.poll(a.token).incoming);});
test('HTTP API: two separate bearer sessions, CORS and private state',async()=>{const server=createCafeServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base=`http://127.0.0.1:${server.address().port}`;const post=async(path,body,token)=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});return r.json();};const a=await post('/api/join',{name:'Один'}),b=await post('/api/join',{name:'Два'});const invited=await post('/api/command',{type:'invite',to:b.id,gameId:'uno'},a.token);const started=await post('/api/command',{type:'respond',id:invited.outgoing.id,accept:true},b.token);assert.equal(started.match.seat,1);assert.ok(started.match.state.hands[0].every(c=>c===null));assert.equal((await fetch(base+'/api/state')).status,401);assert.equal((await fetch(base+'/api/state',{headers:{Origin:'https://example.org'}})).status,403);}finally{await new Promise(r=>server.close(r));}});
