import {deck,shuffle,compare} from './common.js';
export const HAND_NAMES=['Старшая карта','Пара','Две пары','Тройка','Стрит','Флеш','Фулл-хаус','Каре','Стрит-флеш'];
export function rankFive(cards){const ranks=cards.map(c=>c.rank).sort((a,b)=>b-a),groups=[...new Set(ranks)].map(r=>[r,ranks.filter(n=>n===r).length]).sort((a,b)=>b[1]-a[1]||b[0]-a[0]);const flush=cards.every(c=>c.suit===cards[0].suit),unique=[...new Set(ranks)];let straight=unique.length===5&&unique[0]-unique[4]===4?unique[0]:unique.join(',')==='14,5,4,3,2'?5:0;
 if(flush&&straight)return [8,straight];if(groups[0][1]===4)return [7,groups[0][0],groups[1][0]];if(groups[0][1]===3&&groups[1][1]===2)return [6,groups[0][0],groups[1][0]];if(flush)return [5,...ranks];if(straight)return [4,straight];if(groups[0][1]===3)return [3,...groups.map(g=>g[0])];if(groups[0][1]===2&&groups[1][1]===2)return [2,...groups.map(g=>g[0])];if(groups[0][1]===2)return [1,...groups.map(g=>g[0])];return [0,...ranks];}
export function bestHand(cards){if(cards.length<5)return [0,...cards.map(c=>c.rank).sort((a,b)=>b-a)];let best=[];for(let a=0;a<cards.length-4;a++)for(let b=a+1;b<cards.length-3;b++)for(let c=b+1;c<cards.length-2;c++)for(let d=c+1;d<cards.length-1;d++)for(let e=d+1;e<cards.length;e++){const rank=rankFive([cards[a],cards[b],cards[c],cards[d],cards[e]]);if(compare(rank,best)>0)best=rank;}return best;}
export class Poker{
 constructor(count,random=Math.random){this.random=random;this.draw=shuffle(deck(),random);this.hands=Array.from({length:count+1},()=>[this.draw.pop(),this.draw.pop()]);this.board=[];this.stacks=this.hands.map(()=>490);this.pot=this.hands.length*10;this.folded=[];this.bets=this.hands.map(()=>0);this.currentBet=0;this.street=0;this.actor=0;this.raised=false;this.pending=this.hands.map((_,i)=>i);this.done=false;this.message='Техасский холдем. Анте 10. Только игровые фишки.';}
 get unit(){return this.street<2?10:20;}
 get live(){return this.hands.map((_,i)=>i).filter(i=>!this.folded.includes(i));}
 get call(){return this.currentBet-this.bets[this.actor];}
 settle(winners){this.winners=winners;const amount=Math.floor(this.pot/winners.length),extra=this.pot%winners.length;winners.forEach((p,i)=>this.stacks[p]+=amount+(i===0?extra:0));this.awarded=this.pot;this.pot=0;this.done=true;this.message=winners.length>1?'Банк разделён.':'Банк разыгран.';}
 advance(){if(this.live.length===1){this.settle(this.live);return;}if(!this.pending.length){if(this.street===3){const ranked=this.live.map(p=>({p,rank:bestHand([...this.hands[p],...this.board])})).sort((a,b)=>compare(b.rank,a.rank));this.settle(ranked.filter(x=>compare(x.rank,ranked[0].rank)===0).map(x=>x.p));return;}this.street++;this.draw.pop();for(let i=0;i<(this.street===1?3:1);i++)this.board.push(this.draw.pop());this.bets.fill(0);this.currentBet=0;this.raised=false;this.pending=this.live;this.actor=this.pending[0];return;}
 let p=this.actor;do{p=(p+1)%this.hands.length;}while(!this.pending.includes(p));this.actor=p;
 }
 act(a){if(this.done)return false;const p=this.actor;if(!['fold','call','raise'].includes(a.type))return false;if(a.type==='raise'&&this.raised)return false;this.pending=this.pending.filter(i=>i!==p);if(a.type==='fold'){this.folded.push(p);this.message='Пас.';}else{const cost=this.call+(a.type==='raise'?this.unit:0);if(cost>this.stacks[p])return false;this.stacks[p]-=cost;this.bets[p]+=cost;this.pot+=cost;if(a.type==='raise'){this.currentBet=this.bets[p];this.raised=true;this.pending=this.live.filter(i=>i!==p);this.message='Ставка повышена.';}else this.message=cost?'Ставка уравнена.':'Чек.';}this.advance();return true;}
 bot(){const h=this.hands[this.actor],rank=bestHand([...h,...this.board]),strong=this.board.length?rank[0]>=2:h[0].rank===h[1].rank||Math.min(h[0].rank,h[1].rank)>=11;const r=this.random();return this.act({type:this.call&&!strong&&r<.18?'fold':!this.raised&&strong&&r<.6?'raise':'call'});}
}
