import {GAMES} from './registry.js';
import {newNames,cardText} from './common.js';
import {UNO_COLORS} from './uno.js';
import {bestHand,HAND_NAMES} from './poker.js';
import './games.css';
const colorNames={red:'Красный',yellow:'Жёлтый',green:'Зелёный',blue:'Синий',wild:'Любой цвет'};
const unoText=c=>({wild:'✦',reverse:'⇄',skip:'⊘'})[c.value]||c.value;
export function installGameUI({onOpen=()=>{},onClose=()=>{}}={}){
 const dialog=document.createElement('dialog');dialog.id='game-room';dialog.setAttribute('aria-labelledby','game-room-title');document.body.append(dialog);
 let selected=GAMES.find(g=>g.id==='uno'),game=null,names=[],timer=null,epoch=0,wild='red',target=0,from=null,opponents=1;
 function stop(){epoch++;clearTimeout(timer);timer=null;}
 function close(){stop();dialog.close();onClose();}
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 function open(id){onOpen();if(!dialog.open)dialog.showModal();if(id&&!game)selected=GAMES.find(g=>g.id===id)||selected;render();schedule();}
 function schedule(){if(timer||!dialog.open||!game||game.done||(game.actor===0&&selected.id!=='croissant'))return;const token=epoch;timer=setTimeout(()=>{timer=null;if(token!==epoch||!dialog.open)return;if(selected.id==='croissant')game.tick(.65);else game.bot();target=game.table?.findIndex(p=>!p.defense)??0;from=null;render();schedule();},650);}
 function card(c,{disabled=false,action='',active=false}={}){const uno=selected.id==='uno',label=uno?`${colorNames[c.color]}, ${unoText(c)}`:cardText(c);return `<button class="playing-card ${uno?'uno-card '+c.color:['♥','♦'].includes(c.suit)?'red-suit':''} ${active?'chosen':''}" ${disabled?'disabled':''} ${action} aria-label="${label}"><small>${uno?unoText(c):cardText(c)}</small><b>${uno?unoText(c):c.suit}</b></button>`;}
 function result(){if(!game.done)return '';let text;if(selected.id==='durak')text=game.loser<0?'Ничья':game.loser===0?'В этот раз вы остались с картами':`${names[game.loser]} остался с картами`;else if(selected.id==='poker')text=game.winners.map(p=>names[p]).join(' и ')+` — банк ${game.awarded}`;else text=game.winner===null?'Ничья':game.winner===0?'Вы выиграли!':`${names[game.winner]} побеждает`;return `<div class="game-result" role="status"><span>ПАРТИЯ ЗАВЕРШЕНА</span><h2>${text}</h2><button class="game-primary" data-do="restart">Новая партия</button></div>`;}
 function hand(){if(['checkers','croissant'].includes(selected.id))return '';const h=game.hands[0];return `<section class="your-hand"><div class="hand-heading"><strong>Ваши карты · ${h.length}</strong><span>${selected.id==='poker'?'Никто не видит ваши карты':game.actor===0&&!game.done?'Выберите карту для хода':'Соперник думает…'}</span></div><div class="hand-cards">${h.map(c=>{let disabled=game.actor!==0||game.done||selected.id==='poker';if(selected.id==='uno')disabled||=!game.legal(c);if(selected.id==='durak')disabled||=game.actor===game.attacker?!game.canAttack(c):!game.table[target]||!!game.table[target].defense||!game.beats(c,game.table[target].attack);return card(c,{disabled,action:`data-card="${c.id}"`});}).join('')}</div></section>`;}
 function actions(){if(game.done||game.actor!==0)return '';if(selected.id==='uno')return `<div class="wild-colors" aria-label="Цвет для джокера">Цвет джокера: ${UNO_COLORS.map(c=>`<button data-color="${c}" class="${c} ${wild===c?'selected':''}" aria-label="${colorNames[c]} для джокера" aria-pressed="${wild===c}">${wild===c?'✓':''}</button>`).join('')}</div><button data-action="${game.drawn===null?'draw':'pass'}" class="game-primary">${game.drawn===null?'Взять карту':'Оставить карту и пропустить'}</button>`;
 if(selected.id==='durak')return game.actor===game.defender?'<button data-action="take" class="game-primary">Взять карты</button>':game.table.length&&(game.taking||game.table.every(p=>p.defense))?`<button data-action="end" class="game-primary">${game.taking?'Закончить подкидывание':'Бито'}</button>`:'';
 if(selected.id==='poker')return `<button data-action="fold" class="game-secondary">Пас</button><button data-action="call" class="game-primary">${game.call?'Колл · '+game.call:'Чек'}</button><button data-action="raise" class="game-secondary" ${game.raised?'disabled':''}>Повысить до ${game.currentBet+game.unit}</button>`;return '';}
 function table(){switch(selected.id){case 'croissant':return `<div class="croissant-clock"><span>ВЫПЕЧКА НА СВОБОДЕ</span><strong>${Math.ceil(game.remaining)} сек</strong><small>Ваш улов: ${game.scores[0]} 🥐</small></div><div class="croissant-grid">${Array.from({length:12},(_,i)=>`<button class="snack-tile ${i===game.target?'runaway':''}" data-snack="${i}" ${game.done?'disabled':''} aria-label="${i===game.target?'Поймать круассан':i%3?'Не круассан: чашка':'Не круассан: уточка'}">${i===game.target?'🥐':i%3?'☕':'🦆'}</button>`).join('')}</div>`;
case 'uno':return `<div class="uno-center"><div class="card-back"><b>Ю</b><small>Колода · ${game.draw.length}</small></div>${card(game.top,{disabled:true})}<p>Текущий цвет<br><strong>${colorNames[game.color]}</strong><br>${game.direction===1?'→ По часовой':'← Против часовой'}</p></div>`;
 case 'durak':return `<div class="durak-info"><span>Колода: ${game.draw.length}</span><strong>Козырь ${game.trump}</strong><span>Бито: ${game.discard.length}</span></div><div class="battle-table">${game.table.length?game.table.map((p,i)=>`<div class="battle-pair ${target===i?'selected-pair':''}">${card(p.attack,{disabled:game.actor!==0||game.actor!==game.defender||!!p.defense,action:`data-target="${i}"`,active:target===i&&!p.defense})}${p.defense?card(p.defense,{disabled:true}):'<span class="defend-slot">Отбить</span>'}</div>`).join(''):'<div class="table-empty">Новый заход<br><small>Атакует '+names[game.attacker]+'</small></div>'}</div>`;
 case 'poker':return `<div class="poker-pot"><small>${['ПРЕФЛОП','ФЛОП','ТЁРН','РИВЕР'][game.street]}</small><strong>Банк · ${game.pot||game.awarded||0}</strong></div><div class="community-cards">${game.board.map(c=>card(c,{disabled:true})).join('')}${Array.from({length:5-game.board.length},()=>'<div class="empty-card">Ю</div>').join('')}</div><p class="poker-rank">${game.board.length?HAND_NAMES[bestHand([...game.hands[0],...game.board])[0]]:'Общие карты откроются после ставок'}</p>${game.done&&game.live.length>1?`<div class="showdown">${game.live.filter(p=>p!==0).map(p=>`<p>${names[p]}: ${game.hands[p].map(cardText).join(' ')} — ${HAND_NAMES[bestHand([...game.hands[p],...game.board])[0]]}</p>`).join('')}</div>`:''}`;
 case 'checkers':{const moves=game.moves();return `<div class="checker-board" role="group" aria-label="Шашечная доска">${game.board.map((p,i)=>{const r=Math.floor(i/8),c=i%8,dark=(r+c)%2,destination=from!==null&&moves.some(m=>m.from===from&&m.to===i),selectable=p?.player===0&&moves.some(m=>m.from===i);return `<button data-square="${i}" class="square ${dark?'dark':'light'} ${from===i?'selected-square':''} ${destination?'destination':''}" ${!dark||game.actor!==0||game.done||(!destination&&!selectable)?'disabled':''} aria-label="${'abcdefgh'[c]}${8-r}${p?', '+(p.player===0?'ваша':'соперника')+(p.king?' дамка':' шашка'):destination?', доступный ход':''}">${p?`<span class="checker ${p.player===0?'ivory':'charcoal'}">${p.king?'♛':''}</span>`:destination?'•':''}<small>${c===0?8-r:r===7?'abcdefgh'[c]:''}</small></button>`;}).join('')}</div>`;}}
 }
 function render(){const focus=document.activeElement;const focusKey=focus?.dataset?.card?`[data-card="${focus.dataset.card}"]`:focus?.dataset?.color?`[data-color="${focus.dataset.color}"]`:null;
 dialog.innerHTML=`<div class="game-shell"><header class="game-header"><div><span>Ю КОФЕ · ИГРОВАЯ КОМНАТА</span><h1 id="game-room-title">${game?selected.name:'Ещё одну партию?'}</h1></div><button class="game-close" data-do="close">← В кофейню</button></header>${!game?`<div class="game-lobby"><p class="game-lead">Устраивайтесь поудобнее. Компания уже найдётся.</p><div class="game-choices">${GAMES.map(g=>`<button data-game="${g.id}" class="game-choice ${selected.id===g.id?'selected':''}" style="--box-color:${g.color}" aria-pressed="${selected.id===g.id}"><span>${g.icon}</span><strong>${g.name}</strong><small>${g.tag}</small></button>`).join('')}</div><div class="game-setup"><label>Компьютерных соперников <select id="opponent-count" ${selected.max===1?'disabled':''}>${Array.from({length:selected.max},(_,i)=>`<option value="${i+1}" ${opponents===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><button class="game-primary" data-do="start">Начать · ${selected.name} →</button></div><details open class="game-rules"><summary>Как играем</summary><p>${selected.rules}</p></details><p class="game-footnote">Новая партия — новая компания. Прогресс текущей партии сохраняется, пока открыта страница.</p></div>`:`<div class="game-toolbar"><button data-do="lobby">← Выбрать игру</button><button data-do="restart">Новая партия</button><details><summary>Правила</summary><p>${selected.rules}</p></details></div><div class="opponents">${names.slice(1).map((n,i)=>{const p=i+1;return `<div class="opponent ${game.actor===p&&!game.done?'thinking':''} ${game.folded?.includes(p)||game.out?.includes(p)?'inactive':''}"><span class="avatar">${n[0]}</span><div><strong>${n}</strong><small>${selected.id==='croissant'?`${game.scores[p]} круассанов`:selected.id==='checkers'?'Тёмные шашки':selected.id==='poker'?game.folded.includes(p)?'Пас':`${game.stacks[p]} фишек · ставка ${game.bets[p]}`:game.out?.includes(p)?'Вышел из игры':`${game.hands[p].length} карт`}</small></div>${game.actor===p&&!game.done?'<i>•••</i>':''}</div>`;}).join('')}</div><div class="turn-status" role="status">${game.done?'Партия завершена':selected.id==='croissant'?'Ловите круассаны!':game.actor===0?'Ваш ход':names[game.actor]+' думает…'} <small>${game.message}</small></div><main class="game-table ${selected.id}">${table()}${result()}</main>${selected.id==='poker'?`<div class="your-stack">У вас ${game.stacks[0]} фишек${game.folded.includes(0)?' · Вы в пасе':''}</div>`:''}${hand()}<div class="game-actions">${actions()}</div>`}</div>`;
 if(focusKey)dialog.querySelector(focusKey)?.focus({preventScroll:true});
 }
 dialog.addEventListener('change',e=>{if(e.target.id==='opponent-count')opponents=Number(e.target.value);});
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
  if(d.do==='close'){close();return;}if(d.game){selected=GAMES.find(g=>g.id===d.game);opponents=Math.min(opponents,selected.max);render();return;}if(d.do==='lobby'){stop();game=null;render();return;}
  if(d.do==='start'||d.do==='restart'){stop();names=newNames(Math.min(opponents,selected.max));game=selected.create(names.length-1);target=0;from=null;render();schedule();return;}
  if(d.color){wild=d.color;render();return;}if(!game||game.done||game.actor!==0)return;
  if(d.target!==undefined){target=Number(d.target);render();return;}
  if(d.snack!==undefined){game.act({slot:Number(d.snack)});render();return;}
  if(d.square!==undefined){const square=Number(d.square);if(from!==null&&game.moves().some(m=>m.from===from&&m.to===square)){game.act({from,to:square});from=game.forced;}else from=square;render();schedule();return;}
  if(d.card!==undefined){const id=selected.id==='uno'?Number(d.card):d.card;game.act({type:'play',id,color:wild,target});target=game.table?.findIndex(p=>!p.defense)??0;}else if(d.action)game.act({type:d.action});render();schedule();
 });
 return {open,close,get opened(){return dialog.open;}};
}
