import {shuffle} from './common.js';
export const UNO_COLORS=['red','yellow','green','blue'];
export class Uno{
 constructor(count,random=Math.random){this.random=random;this.hands=Array.from({length:count+1},()=>[]);this.pile=[];this.draw=[];let id=0;for(const color of UNO_COLORS){this.draw.push({id:id++,color,value:'0'});for(const value of ['1','2','3','4','5','6','7','8','9','skip','reverse','+2'])for(let j=0;j<2;j++)this.draw.push({id:id++,color,value});}for(let i=0;i<4;i++)for(const value of ['wild','+4'])this.draw.push({id:id++,color:'wild',value});shuffle(this.draw,random);for(let i=0;i<7;i++)for(const h of this.hands)h.push(this.draw.pop());let start=this.draw.findIndex(c=>/^\d$/.test(c.value));this.pile.push(this.draw.splice(start,1)[0]);this.color=this.top.color;this.actor=0;this.direction=1;this.drawn=null;this.done=false;this.message='Совпадение по цвету или значению. Ваш ход.';}
 get top(){return this.pile.at(-1);}
 next(n=1){this.actor=(this.actor+n*this.direction+this.hands.length*4)%this.hands.length;this.drawn=null;}
 pull(p,n){for(let i=0;i<n;i++){if(!this.draw.length&&this.pile.length>1){const top=this.pile.pop();this.draw=shuffle(this.pile,this.random);this.pile=[top];}if(this.draw.length)this.hands[p].push(this.draw.pop());}}
 legal(c){return (this.drawn===null||c.id===this.drawn)&&(c.color==='wild'||c.color===this.color||c.value===this.top.value)&&(c.value!=='+4'||!this.hands[this.actor].some(x=>x.color===this.color));}
 act(a){if(this.done)return false;const h=this.hands[this.actor];if(a.type==='draw'&&this.drawn===null){const n=h.length;this.pull(this.actor,1);this.drawn=h.length>n?h.at(-1).id:-1;if(!h.some(c=>this.legal(c)))this.next();this.message='Взята карта из колоды.';return true;}if(a.type==='pass'&&this.drawn!==null){this.next();return true;}if(a.type!=='play')return false;const i=h.findIndex(c=>c.id===a.id);if(i<0||!this.legal(h[i]))return false;const c=h.splice(i,1)[0];this.pile.push(c);this.color=c.color==='wild'?(UNO_COLORS.includes(a.color)?a.color:'red'):c.color;const winner=this.actor;
 let skip=1;if(c.value==='reverse'){this.direction*=-1;if(this.hands.length===2)skip=2;}if(c.value==='skip')skip=2;if(c.value==='+2'||c.value==='+4'){const victim=(this.actor+this.direction+this.hands.length)%this.hands.length;this.pull(victim,c.value==='+2'?2:4);skip=2;}
 this.message=h.length===1?'УНО! Осталась одна карта.':'Карта сыграна.';this.next(skip);if(!h.length){this.done=true;this.winner=winner;this.message='Все карты сброшены!';}return true;}
 bot(){const h=this.hands[this.actor],c=h.find(c=>this.legal(c));if(c){const color=UNO_COLORS.toSorted((a,b)=>h.filter(c=>c.color===b).length-h.filter(c=>c.color===a).length)[0];return this.act({type:'play',id:c.id,color});}return this.act({type:this.drawn===null?'draw':'pass'});}
}
