import {OnlineClient} from './client.js';
import {installGuests} from './guests.js';
import {GAMES} from '../games/registry.js';
import {cleanName,escapeHTML as esc} from './protocol.js';
import './online.css';

export function installOnline({scene,canvas,camera,world,keys,interaction,gameRoom}){
 const base=import.meta.env.VITE_ONLINE_URL||(import.meta.env.DEV||location.hostname.endsWith('.vercel.app')?'':null);
 const launch=document.createElement('button');launch.className='quiet';launch.id='online-guests';launch.textContent='Гости · онлайн';document.querySelector('.header-actions').prepend(launch);
 const dialog=document.createElement('dialog');dialog.id='online-lobby';dialog.setAttribute('aria-labelledby','online-title');document.body.append(dialog);
 const toast=document.createElement('div');toast.className='online-toast';toast.setAttribute('role','status');toast.hidden=true;document.body.append(toast);let toastTimer;
 function notice(message){toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,5000);}
 const client=base!==null?new OnlineClient(base):null;let state=null,selected=null,mode='guests',gameId='uno',invitation=null,lastMatch=null,nameDraft='',signature='';
 const guests=installGuests({scene,canvas,camera,world,onSelect:id=>{selected=id;mode='person';open();}});
 function open(){keys.clear();document.exitPointerLock?.();interaction.hide();if(!dialog.open)dialog.showModal();render();}
 function render(){const people=state?.guests.filter(g=>g.id!==state.id)||[],person=people.find(p=>p.id===selected),incoming=state?.incoming,self=state?.guests.find(p=>p.id===state.id);
 dialog.innerHTML=`<div class="online-panel"><header><div><small>Ю КОФЕ · ВСТРЕЧИ</small><h2 id="online-title">${incoming?'Вас приглашают играть':mode==='name'?'Как вас зовут?':mode==='person'&&person?esc(person.name):'Гости кофейни'}</h2></div><button data-close aria-label="Закрыть гостей">×</button></header>
 ${!client?'<p>Онлайн-зал скоро откроется. Пока можно сыграть с компьютером.</p>':!client.connected?'<p role="status">Подключаемся к общему залу… При потере связи гости появятся снова автоматически.</p>':incoming?`<p><b>${esc(incoming.name)}</b> предлагает сыграть в «${esc(GAMES.find(g=>g.id===incoming.gameId)?.name)}». Сыграть?</p><div class="online-actions"><button data-answer="yes">Да, сыграть</button><button data-answer="no">Нет, спасибо</button></div>`:mode==='name'?`<form id="guest-name-form"><label for="guest-name">Имя, которое увидят другие гости</label><input id="guest-name" name="name" maxlength="24" autocomplete="nickname" value="${esc(nameDraft)}" placeholder="Например, Юрий" required><button type="submit">Сохранить имя</button></form>`:mode==='person'&&person?`<p>${person.busy?'Гость сейчас играет. Можно пригласить его после партии.':'Пригласите гостя за игровой стол.'}</p><label for="invite-game">Выберите игру</label><select id="invite-game">${GAMES.map(g=>`<option value="${g.id}" ${g.id===gameId?'selected':''}>${g.icon} ${g.name}</option>`).join('')}</select><button data-invite ${person.busy||self?.busy||state.outgoing?'disabled':''}>Предложить игру</button><button data-back>← Все гости</button>`:`<div class="online-self"><span>Вы: <b>${esc(self?.name||'Гость')}</b></span><button data-name>Ввести своё имя</button></div><p class="online-muted">Нажмите на гостя в кофейне или выберите его здесь.</p><div class="guest-list">${people.length?people.map(p=>`<button data-guest="${p.id}"><span class="guest-initial">${esc(p.name[0])}</span><span><b>${esc(p.name)}</b><small>${p.busy?'Играет':'Предложить игру →'}</small></span></button>`).join(''):'<p>Пока вы здесь одни. Пришлите другу ссылку на кофейню — он появится рядом.</p>'}</div>${state.match?'<button data-resume>Вернуться в совместную партию</button>':''}`}
 ${state?.outgoing?'<div class="invite-wait" role="status">Приглашение отправлено. Ждём ответа…<button data-cancel>Отменить</button></div>':''}</div>`;
 }
 launch.onclick=()=>{mode='guests';open();};dialog.addEventListener('input',e=>{if(e.target.id==='guest-name')nameDraft=e.target.value;});dialog.addEventListener('change',e=>{if(e.target.id==='invite-game')gameId=e.target.value;});
 dialog.addEventListener('submit',e=>{e.preventDefault();const name=cleanName(nameDraft);try{localStorage.setItem('yu-guest-name',name);}catch{}mode='guests';client?.command({type:'name',name});});
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if('close'in d){dialog.close();return;}if('name'in d){mode='name';nameDraft=state?.guests.find(g=>g.id===state.id)?.name||'';render();dialog.querySelector('input')?.focus();return;}if(d.guest){selected=d.guest;mode='person';render();return;}if('back'in d){mode='guests';render();return;}if('invite'in d)client?.command({type:'invite',to:selected,gameId});if('cancel'in d)client?.command({type:'cancel'});if(d.answer)client?.command({type:'respond',id:state.incoming.id,accept:d.answer==='yes'});if('resume'in d){dialog.close();gameRoom.open();}});
 if(client){gameRoom.setOnlineHandler(a=>client.command(a));client.addEventListener('connection',e=>{gameRoom.setConnection(e.detail);launch.textContent=e.detail?`Гости · ${state?.guests.length||1}`:'Гости · подключение…';if(!e.detail)guests.update([],null);});client.addEventListener('notice',e=>notice(e.detail));client.addEventListener('state',e=>{state=e.detail;guests.update(state.guests,state.id);if(state.notice){notice(state.notice);setTimeout(()=>client.command({type:'ack'}),20);}if(state.match){if(lastMatch!==state.match.id){dialog.close();lastMatch=state.match.id;}gameRoom.updateOnline(state.match);}else if(lastMatch){lastMatch=null;gameRoom.endOnline();}
  if(state.incoming&&invitation!==state.incoming.id){invitation=state.incoming.id;open();}if(!state.incoming)invitation=null;const next=JSON.stringify([state.guests,state.incoming,state.outgoing,!!state.match]);if(next!==signature){signature=next;if(dialog.open&&mode!=='name')render();}
 });client.start();}
 return client;
}
