import * as T from 'three';
import {isTap} from './barista-interaction.js';
import './music.css';
import {assetUrl} from './asset-url.js';
import {createWallDarbuka,hitWallDarbuka} from './music-prop.js';

import {INSTRUMENTS,createMusicAudio,getMusicPreset} from './music-audio.js';
import {installMusicPointers} from './music-gestures.js';
import {UKULELE_CHORDS} from './music-instruments.js';
import {handpanPosition,KIT_POSITIONS,MUSIC_KEYS,MUSIC_CODES as CODES,isSustained} from './music-layouts.js';

export function installMusic({scene,canvas,camera,world,keys,interaction}){
 const drum=createWallDarbuka(scene),audio=createMusicAudio(),settings=new Map();let selected=null,revision=0,disposePointers=()=>{};
 const launcher=document.createElement('button');launcher.className='quiet';launcher.id='open-music';launcher.textContent='Музыка ♫';document.querySelector('.header-actions').prepend(launcher);
 const dialog=document.createElement('dialog');dialog.id='music-room';dialog.setAttribute('aria-labelledby','music-title');document.body.append(dialog);
 const open=()=>{keys.clear();interaction.hide();document.exitPointerLock?.();selected=null;render();dialog.showModal();};launcher.onclick=open;
 const finish=()=>{revision++;disposePointers.clear?.();audio.stop();heldKeys.clear();keys.clear();};dialog.addEventListener('close',()=>{finish();launcher.focus({preventScroll:true});});
 const get=()=>settings.get(selected.id);
 const labels=()=>selected.id==='ukulele'&&get().mode==='chords'?UKULELE_CHORDS.map(c=>c.label):selected.labels;
 function render(){
  revision++;disposePointers();audio.stop();heldKeys.clear();
  dialog.innerHTML=`<div class="music-top"><span>Ю КОФЕ / МУЗЫКАЛЬНАЯ КОМНАТА</span><button data-close aria-label="Закрыть музыкальную комнату">✕</button></div><h2 id="music-title">${selected?selected.name:'Поймай свой ритм'}</h2><p class="music-intro">${selected?'Касайся площадок или играй клавишами, указанными на площадках. '+(isSustained(selected)?'Веди палец по нотам для плавного перехода. Два пальца — две независимые ноты.':'Веди палец по площадкам и играй несколькими пальцами. Shift — акцент.'):'Выбери инструмент. Здесь можно играть, экспериментировать и просто слушать.'}</p>`;
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();
  if(!selected){const grid=document.createElement('div');grid.className='music-instruments';INSTRUMENTS.forEach(inst=>{const b=document.createElement('button');b.innerHTML=`<span class="music-icon">${inst.icon}</span><strong>${inst.name}</strong><small>Живая запись · 3 пресета ↗</small>`;b.onclick=()=>{selected=inst;if(!settings.has(inst.id))settings.set(inst.id,{...getMusicPreset(inst.id),preset:'0'});render();dialog.querySelector('[data-back]').focus();};grid.append(b);});dialog.append(grid);return;}
  const controls=document.createElement('div');controls.innerHTML=`<div class="music-toolbar"><button data-back>← Все инструменты</button><label>Характер звука <select aria-label="Пресет">${selected.presets.map((p,i)=>`<option value="${i}">${p}</option>`).join('')}<option value="custom">Свой звук</option></select></label></div><div class="music-mode"></div><div class="music-pads"></div><div class="music-settings"></div><p class="music-status" role="status">Загружаем записи инструмента…</p>`;dialog.append(controls);
  controls.querySelector('[data-back]').onclick=()=>{selected=null;render();dialog.querySelector('.music-instruments button').focus();};const preset=controls.querySelector('select');preset.value=get().preset;
  preset.onchange=()=>{if(preset.value==='custom'){get().preset='custom';return;}Object.assign(get(),getMusicPreset(selected.id,+preset.value),{preset:preset.value});render();dialog.querySelector('select').focus();};
  if(selected.id==='ukulele'){
   const mode=controls.querySelector('.music-mode');mode.setAttribute('role','group');mode.setAttribute('aria-label','Режим укулеле');
   for(const [value,label] of [['notes','Ноты'],['chords','Аккорды']]){const button=document.createElement('button');button.textContent=label;button.dataset.mode=value;button.setAttribute('aria-pressed',String((get().mode||'notes')===value));button.onclick=()=>{get().mode=value;render();dialog.querySelector(`[data-mode="${value}"]`).focus();};mode.append(button);}
   const hint=document.createElement('span');hint.textContent=get().mode==='chords'?'28 аккордов · четыре струны':'15 нот · две октавы';mode.append(hint);
  }
  const padArea=controls.querySelector('.music-pads');
  padArea.classList.toggle('expanded',labels().length>8);
  padArea.classList.toggle('handpan-layout',selected.id==='handpan');padArea.classList.toggle('kit-layout',selected.id==='kit');
  if(['handpan','kit'].includes(selected.id)){const hint=document.createElement('p');hint.className='music-layout-hint';hint.textContent=selected.id==='handpan'?'Бас в центре · гамма чередуется справа и слева по кругу':'Вид сверху · все кнопки одинакового размера';padArea.after(hint);}

  labels().forEach((label,i)=>{const b=document.createElement('button'),inst=selected;b.className=`music-pad ${inst.type}`;b.dataset.note=i;
   if(inst.id==='handpan'||inst.id==='kit'){const [x,y]=inst.id==='handpan'?handpanPosition(i):KIT_POSITIONS[i];b.style.setProperty('--pad-x',x+'%');b.style.setProperty('--pad-y',y+'%');if(inst.id==='handpan'&&i===0)b.classList.add('ding');if(inst.id==='kit'&&[2,3,7,8,10].includes(i))b.classList.add('cymbal');}
   b.setAttribute('aria-label',label+(MUSIC_KEYS[i]?' · клавиша '+MUSIC_KEYS[i]:''));b.innerHTML=`<kbd>${MUSIC_KEYS[i]||''}</kbd><span>${label}</span>`;
   b.onclick=e=>{if(e.detail===0){hit(i,b).then(release=>{if(isSustained(inst))setTimeout(()=>{release?.();b.classList.remove('playing');},800);});}};controls.querySelector('.music-pads').append(b);});
  disposePointers=installMusicPointers(padArea,{sustained:isSustained(selected),start:(i,v)=>hit(i,padArea.querySelector(`[data-note="${i}"]`),v),onNote:i=>{controls.querySelector('.music-status').textContent=`${selected.name} · ${labels()[i]}`;}});
  for(const [key,label,min,max,step] of [['volume','Громкость',0,1,.01],['tone','Яркость',0,1,.01],['decay',isSustained(selected)?'Послезвучие':'Длина звука',0,1,.01],['space','Пространство',0,1,.01],['tune','Строй',-12,12,1]]){const l=document.createElement('label');l.innerHTML=`<span>${label} <output>${key==='tune'?get()[key]+' пт':Math.round(get()[key]*100)+'%'}</output></span><input type="range" aria-label="${label}" min="${min}" max="${max}" step="${step}" value="${get()[key]}">`;l.querySelector('input').oninput=e=>{get()[key]=+e.target.value;audio.update(get());get().preset='custom';preset.value='custom';l.querySelector('output').textContent=key==='tune'?e.target.value+' пт':Math.round(+e.target.value*100)+'%';};controls.querySelector('.music-settings').append(l);}
  const credits=document.createElement('details');credits.className='music-credits';credits.innerHTML=`<summary>Живые записи · авторы и лицензии</summary><p>Укулеле — <a href="https://freesound.org/people/iainmccurdy/packs/38906/" target="_blank" rel="noopener">Iain McCurdy</a>; хендпан — <a href="https://tonewright.app/instruments/handpan/" target="_blank" rel="noopener">The Sample Shack / ToneWright</a> (WTFPL). Укулеле — CC BY 4.0. Дудук — <a href="https://freesound.org/people/ethnictune/sounds/352572/" target="_blank" rel="noopener">ethnictune</a>; чайна — <a href="https://freesound.org/people/ankealtd/sounds/696255/" target="_blank" rel="noopener">ankealtd</a> (CC0). Дарбука, рамочный барабан и диджириду — <a href="https://github.com/sgossner/VCSL" target="_blank" rel="noopener">Versilian Studios</a>. Бас — <a href="https://github.com/sfzinstruments/karoryfer.growlybass" target="_blank" rel="noopener">Karoryfer Samples</a>. Ударная установка — <a href="https://github.com/sfzinstruments/virtuosity_drums" target="_blank" rel="noopener">Virtuosity Drums / Austin McMahon</a> (CC0). Записи обрезаны, выровнены по уровню и настроены по высоте; у диджириду подготовлены петли. <a href="${assetUrl('audio/music/credits.json')}" target="_blank" rel="noopener">Все источники и условия</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.</p>`;controls.append(credits);
  const version=revision,inst=selected,pads=[...controls.querySelectorAll('.music-pad')],status=controls.querySelector('.music-status');
  const prepare=async()=>{pads.forEach(b=>b.disabled=true);status.textContent='Загружаем записи инструмента…';try{await audio.ready(inst);if(!controls.isConnected||selected!==inst)return;pads.forEach(b=>b.disabled=false);status.textContent='Живые записи готовы. Играй касанием или клавишами · Shift — акцент.';}catch(error){if(!controls.isConnected||selected!==inst)return;status.textContent=error.message+' ';const retry=document.createElement('button');retry.textContent='Повторить загрузку';retry.onclick=prepare;status.append(retry);}};
  if(audio.isReady(inst))status.textContent='Живые записи готовы. Shift — акцент.';else prepare();
 }
 async function hit(i,b,velocity=.8){if(b.disabled)return;const version=revision,inst=selected;try{await audio.ready(inst);if(version!==revision||!dialog.open)return;const release=audio.play(inst,i,get(),velocity);b.classList.add('playing');if(!isSustained(inst))setTimeout(()=>b.classList.remove('playing'),inst.id==='darbuka'&&i>=4?(i===4?170:320):160);dialog.querySelector('.music-status').textContent=`${inst.name} · ${labels()[i]}`;return release;}catch(e){if(dialog.open&&revision===version)dialog.querySelector('.music-status').textContent='Не удалось включить звук: '+e.message;}}
 const heldKeys=new Map();document.addEventListener('keydown',e=>{if(!dialog.open||!selected||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;const i=CODES.indexOf(e.code);if(i<0||i>=labels().length)return;e.preventDefault();e.stopPropagation();if(e.repeat||heldKeys.has(e.code))return;const press={},inst=selected;heldKeys.set(e.code,press);hit(i,dialog.querySelector(`[data-note="${i}"]`),e.shiftKey?1:.8).then(release=>{if(heldKeys.get(e.code)===press)press.release=isSustained(inst)?release:null;else if(isSustained(inst))release?.();});});
 document.addEventListener('keyup',e=>{heldKeys.get(e.code)?.release?.();heldKeys.delete(e.code);dialog.querySelector(`[data-note="${CODES.indexOf(e.code)}"]`)?.classList.remove('playing');});
 const silence=()=>{finish();dialog.querySelectorAll('.playing').forEach(b=>b.classList.remove('playing'));};
 addEventListener('blur',silence);document.addEventListener('visibilitychange',()=>{if(document.hidden)silence();});
 let down=null;const ray=new T.Raycaster(),pointer=new T.Vector2();canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});canvas.addEventListener('click',e=>{if(dialog.open||document.querySelector('dialog[open]')||!isTap(down,e))return;const rect=canvas.getBoundingClientRect(),locked=document.pointerLockElement===canvas;pointer.set(locked?0:(e.clientX-rect.left)/rect.width*2-1,locked?0:1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);if(!hitWallDarbuka(ray,drum,Object.values(world.groups)))return;e.preventDefault();e.stopImmediatePropagation();open();},true);
 return {get opened(){return dialog.open;}};
}
