import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export function propFactory(m){
 function box(g,name,x,y,z,w,h,d,material=m.dark,round=0){const mesh=new T.Mesh(round?new RoundedBoxGeometry(w,h,d,2,round):new T.BoxGeometry(w,h,d),material);mesh.name=name;mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
 function cyl(g,name,x,y,z,rt,rb,h,material=m.metal,segments=20){const mesh=new T.Mesh(new T.CylinderGeometry(rt,rb,h,segments),material);mesh.name=name;mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
 function sphere(g,name,x,y,z,r,material){const o=new T.Mesh(new T.SphereGeometry(r,/muffin|tip-cat|coloured-service-bell|bird-body/.test(name)?32:12,/muffin|tip-cat|coloured-service-bell|bird-body/.test(name)?20:8),material);o.name=name;o.position.set(x,y,z);g.add(o);return o;}
 function rod(g,a,b,r,material=m.black){const start=new T.Vector3(...a),end=new T.Vector3(...b);const o=cyl(g,'tube',...(start.clone().add(end).multiplyScalar(.5).toArray()),r,r,start.distanceTo(end),material,8);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),end.sub(start).normalize());return o;}
 function plane(g,name,x,y,z,w,h,material,rot=0){const o=new T.Mesh(new T.PlaneGeometry(w,h),material);o.name=name;o.position.set(x,y,z);o.rotation.y=rot;g.add(o);return o;}
 function text(g,str,x,y,z,w,h,{color='#eee8c8',background=null,size=100,rot=0}={}){const c=document.createElement('canvas');c.width=1024;c.height=Math.max(128,Math.round(1024*h/w));const ctx=c.getContext('2d');if(background){ctx.fillStyle=background;ctx.fillRect(0,0,c.width,c.height);}ctx.fillStyle=color;ctx.font=`500 ${size}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';str.split('\n').forEach((s,i,a)=>ctx.fillText(s,512,c.height/2+(i-(a.length-1)/2)*size*1.12));const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return plane(g,'lettering',x,y,z,w,h,new T.MeshStandardMaterial({map:t,transparent:true,roughness:.8,side:T.DoubleSide}),rot);}
 function sofa(g,x,z,length,rot,material=m.fabric){const s=new T.Group();s.name='sofa-video';s.position.set(x,0,z);s.rotation.y=rot;g.add(s);box(s,'base',0,.24,0,length,.35,.72,m.dark,.04);box(s,'back',0,.67,-.29,length,.78,.14,material,.05);for(let i=0;i<3;i++){box(s,'seat-cushion',-length/2+(i+.5)*length/3,.48,.05,length/3-.018,.17,.61,material,.055);for(const dz of [-.08,.18])sphere(s,'tuft',-length/2+(i+.5)*length/3,.568,dz,.013,m.dark);const p=box(s,'back-cushion',-length/2+(i+.5)*length/3,.76,-.14,length/3-.055,.47,.14,material,.06);p.rotation.x=-.12;}
 for(const side of [-1,1])box(s,'arm',side*(length/2-.04),.56,0,.09,.49,.78,material,.03);
 for(const x of [-length*.28,length*.25]){const p=box(s,'yellow-pillow',x,.79,.03,.36,.36,.12,material===m.fabric?m.yellow:m.fabric,.065);p.rotation.z=x*.13;p.rotation.x=-.15;}return s;}
 function table(g,x,z){cyl(g,'round-oak-top',x,.69,z,.34,.34,.035,m.wood,48);cyl(g,'lower-shelf',x,.27,z,.25,.25,.025,m.wood,32);for(let i=0;i<3;i++){let a=i*Math.PI*2/3;rod(g,[x+Math.cos(a)*.21,.68,z+Math.sin(a)*.21],[x+Math.cos(a)*.29,.025,z+Math.sin(a)*.29],.018);}}
 function cup(g,x,y,z,r=.045){cyl(g,'cup',x,y+.06,z,r,r*.75,.12,m.white);const h=new T.Mesh(new T.TorusGeometry(r*.6,.01,8,16),m.white);h.position.set(x+r,y+.06,z);g.add(h);cyl(g,'coffee',x,y+.121,z,r*.8,r*.8,.003,m.standard('#3e2719'));}
 function bottle(g,x,y,z,color='#946140'){const glass=m.standard(color,{metalness:.1,roughness:.22});cyl(g,'syrup-bottle',x,y+.13,z,.038,.038,.26,glass);cyl(g,'bottle-neck',x,y+.29,z,.016,.021,.07,glass);cyl(g,'cap',x,y+.34,z,.019,.019,.025,m.black);box(g,'label',x,y+.14,z+.038,.065,.09,.002,m.white);}
 function plant(g,x,y,z,scale=1){const p=new T.Group();p.name='plant';p.position.set(x,y,z);p.scale.setScalar(scale);g.add(p);if(scale>=2){p.scale.setScalar(1);cyl(p,'ficus-pot',0,.2,0,.22,.16,.4,m.standard('#858277'));for(let j=0;j<3;j++)rod(p,[(j-1)*.035,.35,0],[(j-1)*.07,2.35,j*.03],.013,m.standard('#736957'));for(let i=0;i<180;i++){let a=i*2.4,h=.8+(i%31)*.048,r=.16+(i%7)*.055;const lx=Math.cos(a)*r,lz=Math.sin(a)*r; if(i%7===0)rod(p,[0,h-.13,0],[lx,h,lz],.005,m.standard('#5b6143'));const l=sphere(p,'ficus-leaf',lx,h,lz,.065,m.standard(i%2?'#3f5733':'#607346'));l.scale.set(.55,1,.13);l.rotation.set(.6,a,.7);}return p;}cyl(p,'pot',0,.14,0,.15,.1,.28,m.standard('#777875'));cyl(p,'soil',0,.274,0,.137,.137,.01,m.soil);for(let i=0;i<14;i++){const a=i*2.4;let height=.3+(i%5)*.085;rod(p,[0,.25,0],[Math.cos(a)*.22,height,Math.sin(a)*.22],.006,m.standard('#59653a'));const leaf=sphere(p,'leaf',Math.cos(a)*.2,height,Math.sin(a)*.2,.1,m.standard(i%2?'#46653e':'#667a43'));leaf.scale.set(.42,1.3,.14);leaf.rotation.set(.5,a,.5);}return p;}
 return {box,cyl,sphere,rod,plane,text,sofa,table,cup,bottle,plant};
}
